apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: top-trumps
  labels:
    cloud.googleapis.com/location: europe-west1
    run.googleapis.com/startupProbeType: Default
  annotations:
    run.googleapis.com/container-dependencies: '{"top-trumps-ui":["top-trumps-api"]}'
spec:
  template:
    spec:
      containers:
      - name: top-trumps-ui
        image: douglasjohnson/top-trumps-ui:latest
        env:
        - name: API_URL
          value: http://localhost:5000
        ports:
        - containerPort: 8080
        startupProbe:
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 1
          tcpSocket:
            port: 8080
      - name: top-trumps-api
        image: douglasjohnson/top-trumps-api:0.0.1
        env:
          - name: spring.data.mongodb.uri
            valueFrom:
              secretKeyRef:
                key: latest
                name: spring-data-mongodb-uri
          - name: PORT
            value: '5000'
        startupProbe:
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
          tcpSocket:
            port: 5000