name: Deploy

on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: ['main']

permissions:
  contents: read
  id-token: write

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: europe-west1-docker.pkg.dev/spring-boot-open-api-mongodb/top-trumps-ui/top-trumps-ui
      - uses: docker/login-action@v3
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: europe-west1-docker.pkg.dev/spring-boot-open-api-mongodb/top-trumps-ui/top-trumps-ui:latest
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - uses: google-github-actions/deploy-cloudrun@v2
        with:
          region: 'europe-west1'
          metadata: './service.yaml'