name: Deploy

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: read
  id-token: write

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: europe-west1-docker.pkg.dev/spring-boot-open-api-mongodb/top-trumps/top-trumps-ui
      - uses: docker/login-action@v3
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - run: sed -i -e "s/API_IMAGE_VERSION/$API_IMAGE_VERSION/g" -e "s/UI_IMAGE_VERSION/$UI_IMAGE_VERSION/g" service.yaml
        env:
          API_IMAGE_VERSION: 0.0.3
          UI_IMAGE_VERSION: ${{ github.ref_name }}
      - uses: google-github-actions/deploy-cloudrun@v2
        with:
          region: 'europe-west1'
          metadata: './service.yaml'